# version: '3'
services:
  dockernodejs:
    container_name: node
    build: .
    ports:
      - "8000:8000"
  db:
    image: mysql:latest
    container_name: dbNode
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testnode
      MYSQL_USER: soulisack
      MYSQL_PASSWORD: 77477686
    ports: 
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: soulisack
      PMA_PASSWORD: 77477686
    ports:
      - "8080:80"
    depends_on:
      - db
